#@data/values-schema
#@schema/desc "Deployment schema for the CAT+ ChemBord frontend"
---
name: 'catplus-chembord'
version: 'latest'
namespace: 'chembord'

image:
  repository: 'ghcr.io/sdsc-ordes/catplus-chembord'
  tag: 'latest'
  pullPolicy: 'Always'

s3:
  #@schema/desc "Name of existing secret containing all S3 configuration. If provided, fields below will be ignored."
  #@schema/example "my-s3-credentials"
  #@schema/nullable
  existingSecret: ''
  region: ''
  #@schema/desc "Custom (non-AWS) S3 endpoint URL"
  #@schema/example "https://s3.custom-endpoint.example.com"
  endpoint: ''
  bucketName: ''
  accessKeyId: ''
  secretAccessKey: ''

service:
  port: 80

app:
  #@schema/desc "Base path for reverse proxy deployment (e.g., '/chembord' for path-based routing). Leave empty for root deployment."
  #@schema/example "/chembord"
  basePath: ""
  #@schema/desc "Absolute url of the instance"
  #@schema/example "http://localhost:3000"
  origin: ""
  #@schema/desc "URL of the Qlever SPARQL API endpoint."
  #@schema/example "https://catplus.ch/sparql/default"
  qleverApiUrl: ""
  #@schema/desc "URL of the Qlever SPARQL UI endpoint."
  #@schema/example "https://catplus.ch/default"
  qleverUiUrl: ""
  #@schema/desc "URL to SwissCat Project Page."
  #@schema/example "https://www.epfl.ch/research/facilities/swisscat/"
  swisscatUrl: ""
  #@schema/desc "URL to SwissCat Project Page."
  #@schema/example "https://www.datascience.ch/"
  sdscUrl: ""
  #@schema/desc "URL to SwissCat Project Page."
  #@schema/example "https://github.com/sdsc-ordes/catplus-chembord.git"
  chembordGithubUrl: ""
  #@schema/desc "Results per page"
  resultsPerPage: "10"
  #@schema/desc "Catplus Ontology Homepage Url"
  #@schema/example "https://sdsc-ordes.github.io/catplus-ontology/"
  catplusOntologyUrl: "https://sdsc-ordes.github.io/catplus-ontology/"

ingress:
  #@schema/desc "Whether to create an Ingress resource"
  enabled: true
  #@schema/desc "Hostname for the ingress"
  #@schema/example "chembord.example.com"
  host: ''
  #@schema/desc "Path prefix for the ingress rule"
  path: '/'
  #@schema/desc "Path type for the ingress rule (Exact, Prefix, or ImplementationSpecific)"
  pathType: 'Prefix'
  #@schema/desc "Ingress class name"
  className: 'nginx'
  #@schema/nullable
  #@schema/type any=True
  annotations: {}
  tls:
    #@schema/desc "Whether to enable TLS for the ingress"
    enabled: true
    #@schema/desc "Name of the TLS secret"
    #@schema/nullable
    secretName: ''
