name: Build and Push Docker Image

on:
  # Run when merging/pushing to the main branch or pushing a version tag
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

  # Also run when a Pull Request is opened/updated against the main branch
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./tools/image/Dockerfile
          platforms: linux/amd64
          # Only push the image if the event is a 'push' (to main or a tag).
          push: ${{ github.event_name == 'push' }}
          tags: |
            ghcr.io/sdsc-ordes/catplus-chembord:latest
            ghcr.io/sdsc-ordes/catplus-chembord:${{ github.sha }}
